--Every command here will be executed when the container is created

CREATE TABLE CATEGORIES (
    CODE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CATEGORY_NAME VARCHAR(255),
    TAX NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
    CODE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PRODUCT_NAME VARCHAR(255),
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    CATEGORY_CODE INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE)
);


CREATE TABLE ORDERS (
    CODE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2)
);

CREATE TABLE CART(
    CODE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PRODUCT_NAME VARCHAR(255),
    AMOUNT INT,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    PRICE_TAX NUMERIC(10,2),
    TOTAL NUMERIC(10,2)
);

CREATE TABLE ORDER_ITEM(
    CODE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ORDER_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    CODE_CART INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES ORDERS(CODE),
    CONSTRAINT FK_CART FOREIGN KEY (CODE_CART) REFERENCES CART(CODE)
);

